### ISSUE TITLE
Winleafs closes when PC goes to sleep, therefore does not activate lights when PC awakes

### ISSUE THREAD

**Issue by Gibso86** [winleafs/Winleafs#123] opened 2020-06-19 22:26 UTC
Hi guys,

I've set up a schedule for every day at 8am to trigger screen mirror, "turn lights off at application ..." is ticked. This works fine when I sleep my PC, the lights go off. However when I resume the PC Winleafs is no longer loaded, it's closed, so the lights stay off. I have to open winleafs again and the schedule trigger kicks in and the lights work as intended.

When I resume the PC you can see the winleafs icon in the taskbar, but when you hover over it, it disapears, indicating the program has closed.

I've attached logs.

Logs attached.
[logs.txt](https://github.com/winleafs/Winleafs/files/4806887/logs.txt)

Have I done anything wrong to cause this? Help much appreciated!

**Comment by bartdebever** [comment] 2020-06-19 22:31
Thank you for the report, after having a quick look through the code I might have an idea to deploy a fix.
I'll be looking into reproducing the bug soon.

Apologies for the inconvenience

**Comment by Gibso86** [comment] 2020-06-19 22:42
Great, thanks! I should add that it did just seem to work after sleep then
wake. But then the lights stayed on after sleeping again and appear frozen
in color, even after PC wakes.

I unticked "turn lights off...: in my schedule, saved, then reticked the
box and saved again, then put PC to sleep. This then turned the lights off
again.

**Comment by StijnOostdam** [comment] 2020-06-20 12:50
Your logs suggests that you tried to activate Screen mirror at 23:03 and 23:09. Did you do that by hand or was that the schedule?
Could you send more logs from around the time your PC went to sleep? There should be a line where Winleafs sends a request to turn the lights off by sending `state: "off"`. 

And do you have logs from when the PC awakes? My guess is that you don't, since Windows decides to close Winleafs when it goes to sleep. Apperently the lights shut off automatically when the PC goes to sleep, which means Winleafs has been closed. Hence you have to manually start it again.

@bartdebever we should look into preventing Winleafs from closing when the PC goes to sleep.

**Comment by StijnOostdam** [comment] 2020-06-20 12:52
@Gibso86 Suggestion: enable the program to start with Windows, maybe that makes the program start automatically again.

**Comment by Gibso86** [comment] 2020-06-20 13:21
Hi guys, the sleep would of been manual as the schedule is 8am every day, nothing else. I have both 
"Start at windows..." and "Mininimse to tray" ticked in the options. Winleafs is also in my startup folder / apps.

I do not have any more logs atm as I currently have the nanoleafs unplugged to do decorating. I'll add more logs once they are connected again.

I have just noticed however that winleafs now appears to be staying active during sleep and wake. Something to do with the nanoleafs not being live / plugged in? Just tested this 4 times and every time winleafs remained.

**Comment by StijnOostdam** [comment] 2020-06-20 14:06
> I have just noticed however that winleafs now appears to be staying active during sleep and wake. 

Then my assumption has been wrong.

> Something to do with the nanoleafs not being live / plugged in?

Probably yeah.
Please let us know if you have any logs from when your PC goes to sleep and wakes up, that will help us I think.

**Comment by Gibso86** [comment] 2020-06-20 16:59
Hi guys, I've done some more tests for you. I've attached the logs and put a sentence underneath each log entry for each test.
[multi logs.txt](https://github.com/winleafs/Winleafs/files/4808248/multi.logs.txt)

**Comment by StijnOostdam** [comment] 2020-06-22 17:59
Hey, thanks for the extensive testing!
So something odd is happening: in each set of logs there are some failed requests. Some for external control (screen mirror) but also normal commands seem to fail. Any idea why that is happening? Does everything work when you enable screen mirror via the device dropdown (or any other effect)?

Maybe if we know why those requests fail, we can determine what is the problem.

**Comment by Gibso86** [comment] 2020-06-22 19:58
Unfortunately winleafs isn't working at all now...
[logs2.txt](https://github.com/winleafs/Winleafs/files/4815346/logs2.txt)

**Comment by StijnOostdam** [comment] 2020-06-22 21:05
Ah, by chance, that is a crash that I have fixed with my latest commit. That happens when Winleafs checks for updates at startup, but you have no active internet connection (or Github is offline).

Maybe you could try to delete you settings (or make a back up) in %appdata%/Winleafs and try adding your device again

If you download v1.0.5 then your last crash is fixed https://github.com/winleafs/Winleafs/releases/tag/v1.0.5

**Comment by StijnOostdam** [comment] 2020-07-05 09:45
Hey, I have updated the v1.0.5 isntaller with more logging https://github.com/winleafs/Winleafs/releases/tag/v1.0.5. Could you try to reproduce the bug with this new version and give us the new logs?

**Comment by StijnOostdam** [comment] 2020-08-09 14:20
Hey, did you have any chance to try the update?

**Comment by StijnOostdam** [comment] 2020-12-20 20:26
Closing due to inactivity. @Gibso86 or anyone else feel free to open this issue when you encounter this problem again.

**Closed by StijnOostdam** 2020-12-20 20:26 UTC
Labels: bug
